baseURL = "https://xyn-1127.github.io/igd301-blog/"
languageCode = "en-us"
title = "Human-Computer Interaction for Mixed Reality Blog"
theme = "PaperMod"

[params]
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowToc = true
  disableSpecial1stPost = true
  homeInlineGallery = true
  homeInlineGalleryMax = 3
  

[[menu.main]]
  name = "Posts"
  url = "/posts/"
  weight = 1

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          inline = [['$', '$'], ['\\(', '\\)']]
          block = [['$$', '$$'], ['\\[', '\\]']]

